### ISSUE TITLE
Fail to Launch. Stops at pixeled Screen

### ISSUE THREAD

**Issue by huxmut** [nullobject/Arcade-Cave_MiSTer#1]
https://www.youtube.com/watch?v=1fI8yxQZiAM

**Comment by nullobject** [comment]
Thanks for the video. I can see that the CPU is not executing anything real, so my suspicion is with the ROMs.

Would you please be able to verify the ROM file you are using?

    md5sum /media/fat/_Arcade/mame/dodonpach.zip

It should be `9f887a16b6645327384a6623cbebb807`.

If you have a matching ROM file, then we'll have do dig deeper. There may be a bug in the core.

**Comment by huxmut** [comment]
as seen on patreon, 'correct' rom solved the issue. Thanks. Sorry for the pebcak moment :)

**Comment by nullobject** [comment]
All good, I'm happy it was an easy fix :+1:

**Comment by ihallin** [comment]
I'm also getting this issue. Using a ROM with md5sum of `9f887a16b6645327384a6623cbebb807`.

**Comment by huxmut** [comment]
Have a look at my link in the Patreon thread.
RBF in /media/fat/_Arcade/cores
MRA in /media/fat/_Arcade 
ROM in /media/fat/_Arcade/mame

be patient when it starts, takes a little while to fully load.
hitting pause during the load seems to break it. requires a full power down restart

**Comment by nullobject** [comment]
@ihallin Hmm, that's no good. I'll reopen this issue until we're sure it's not a problem with your ROMs.

Like I said, it could certainly be a bug in the core, so I'm not ruling it out yet.

Let me know if you get it working.

**Comment by ihallin** [comment]
@nullobject thanks. I've tried several different sets so far, and only the ones matching the md5 above do anything other than display a black screen. Running 128MB SDRAM. Happy to supply more info or a video if desired.

**Comment by ihallin** [comment]
Just an update on this — another user tested the file I'm using and it was confirmed working for them, so it seems like it's definitely not a ROM issue.

**Comment by huxmut** [comment]
> 
> 
> Just an update on this — another user tested the file I'm using and it was confirmed working for them, so it seems like it's definitely not a ROM issue.

Is your MiSTer rbf the latest, and the linux also updated ??

**Comment by nullobject** [comment]
> Is your MiSTer rbf the latest, and the linux also updated ??

Yep, I am running everything up to date. This is very strange...

**Comment by huxmut** [comment]
two different MiSTers here and both OK.
takes some time to go from the pink screen to the actuall game starting

RBF in /media/fat/_Arcade/cores
MRA in /media/fat/_Arcade
ROM in /media/fat/_Arcade/mame

MD5 however is different at 7b5a8d7cc53bca4b0d2b4323ec86fa84

**Comment by felleg** [comment]
I was having the same issue originally, until I realized that my files were in wrong locations. Here is how I organized my files (and it works!):

```
_Arcade/DoDonPachi.mra
_Arcade/cores/Arcade-Cave_20200815.rbf
games/mame/ddonpach.zip
```

I downloaded ddonpach.zip from a random without having to worry about checksums. For completedness, the checksum of the file I downloaded is:
```
9f887a16b6645327384a6623cbebb807  ddonpach.zip
```

**Comment by nullobject** [comment]
@felleg Thanks for sharing :heart:

There still may be an issue with the core for some folks, but issues with the file placement seems to have been the cause of the problem for most people.

**Comment by ihallin** [comment]
This is the same file placement and checksum that I'm using — still experiencing the pixel screen issue. I actually set it up on a completely different MiSTer unit and still had the same issue.

**Comment by huxmut** [comment]
> 
> 
> This is the same file placement and checksum that I'm using — still experiencing the pixel screen issue. I actually set it up on a completely different MiSTer unit and still had the same issue.

I could flash a copy of my card and post it to you just to try on your hardware and see where the issue lies ...

i wonder if the .ini display resolution has any bearing ???? just grabbing at straw here

**Comment by ihallin** [comment]
Just an update, not sure what happened but with latest MiSTer updates this is working for me now.

**Comment by nullobject** [comment]
@ihallin Glad to hear it :+1:
