### ISSUE TITLE
Core Freezes on Stage 5

### ISSUE THREAD

**Issue by MadSteelDarkness** [nullobject/Arcade-Cave_MiSTer#10]
While checking out the beta today I actually had the core lock up on me twice in Stage 5 towards the end of the stage. [Here's a clip of the first freeze.](https://www.twitch.tv/madsteeldarkness/clip/FragileInexpensiveArtichokeThunBeast?filter=clips&range=30d&sort=time) Otherwise really enjoying the core so far!

**Comment by huxmut** [comment]
Yep, confirming i get this also
somelinks to pics, some with the debug code :)

https://i.ibb.co/KqK8K1s/20200816-155744-HDR.jpg
https://i.ibb.co/NSNJzXt/20200816-155741.jpg
https://i.ibb.co/87W4B7V/20200816-155739-HDR.jpg
https://i.ibb.co/Ws1dG7n/20200816-155736.jpg
https://i.ibb.co/bQshbFq/20200816-155732.jpg

**Comment by nullobject** [comment]
Thanks for the report, will investigate this.

**Comment by terminator2k2** [comment]
ive yet to clear stage 2 without it crashing

**Comment by huxmut** [comment]
Had another freeze today, but not sure it was Lvl 5 or not (sorry, to busy enjoying)

https://ibb.co/bQ8R9g6

different to the Stage 5 lockup though, this was like a 1 second loop repeating

On a side note - any chance of a beta with sound ? i have to have a youtube clip playing in the background to add atmosphere :D

**Comment by nullobject** [comment]
@huxmut Thanks for that.

> On a side note - any chance of a beta with sound ? i have to have a youtube clip playing in the background to add atmosphere :D

Soon, I'm still working on it but the sound chip is getting close to the point where I can roll it into a beta :+1:

**Comment by huxmut** [comment]
Cool, thanks. No pressure, just excitement for the next beta is all.
Thanks :)

**Comment by IcarusFW** [comment]
As an update, the beta does not crash in stage 5, but there's a much bigger issue in the start of stage 6 that makes the game unplayable. (See issue relating to white box layer.)

**Comment by nullobject** [comment]
> As an update, the Dec. 10th beta does not crash in stage 5, but there's a much bigger issue in the start of stage 6 that makes the game unplayable. (See issue relating to white box layer.)

Thanks for the update. The crashing was fixed when I replaced the CPU core.

I will fix the layer priority issues in the other PR :+1:
