### ISSUE TITLE
Pause or Reset breaks display

### ISSUE THREAD

**Issue by akerasi** [nullobject/Arcade-Cave_MiSTer#11]
Not always, but sometimes, Pause or Reset breaks the display in an odd manner; it's as if it can "move" pieces of the display, like this (attached a screenshot of an example)
<img width="181" alt="986506bfa6c86959583d86f92bd0fd70" src="https://user-images.githubusercontent.com/14352170/90325909-972de800-df4f-11ea-873e-b70ae2da81c4.png">

**Comment by Chocobobobo** [comment]
I had the same issue after a crash.
After resetting the game, I had the exact same screen.
Only a cold reboot was able to fix it.

**Comment by nullobject** [comment]
Cool, this is a known issue but thanks for reporting it :heart:

**Comment by nullobject** [comment]
This has been fixed :+1:
