### ISSUE TITLE
Incorrect orientation in vertical aspect ratio

### ISSUE THREAD

**Issue by felleg** [nullobject/Arcade-Cave_MiSTer#12]
I compared the orientation with other upright games (donkey kong, pac-man) and I noticed the screen is flipped compared to these. I don't know if there is a standard in MiSTer for upright games, or if that's what the known bug "Missing menu settings for aspect ratio, screen orientation, flipping, etc." is describing, but I just thought I'd point it out.

**Comment by nullobject** [comment]
@felleg It is a known issue, but it helps to have a ticket for it. Thanks :+1:

**Comment by Manuarcademaniac** [comment]
The orientación its correct. I had the original jamma PCB. Most of vertical games has a anti clockwise orientation by default.. Only some classic like Pacman or bombjack has clockwise orientation and can't changed. THIS IS NOT A BUG on Dodonpachi but the
Dep switches probably has a flip option for clockwise orientation.

**Comment by zakk4223** [comment]
Dodonpachi has a screen flip option in the test menu, which I'm not sure is implemented yet.

**Comment by nullobject** [comment]
@zakk4223 No, not yet.

**Comment by nullobject** [comment]
This has been fixed in beta 4. There are now options for changing the orientation in the MiSTer menu.
