### ISSUE TITLE
Support for different vertical refresh rates?

### ISSUE THREAD

**Issue by ihallin** [nullobject/Arcade-Cave_MiSTer#13]
This isn't really an issue as much as a feature request, but because of DoDonPachi's 57hz vertical refresh rate, the core is unable to sync on my PVM-1351Q monitor (but works fine on other RGB monitors I own). Would it be possible to add a sync adjust feature so that the game can run on a wider range of displays? I realize this detracts from accuracy, but may be necessary for some users to run the core at all.

**Comment by nullobject** [comment]
Fair enough. I would like to revisit the video timings, because at that vertical refresh rate even my Sony PVM needs to have underscan enabled to display the entire picture.

**Comment by mikaeltarquin** [comment]
Is that why I have such a hard time trying to fit the picture in my screen? I tried routing the signal through an Extron RGB to adjust centering, but there's a TON being cutoff regardless of how I center.
[https://imgur.com/a/X1xlBhD](url)

**Comment by nullobject** [comment]
@ihallin @mikaeltarquin Thanks for reporting these issues.

Could you please check out beta 4 and let me know if you still have these issues?

It looks great on my Sony PVM-14M2A. A couple of vertical lines are being clipped at the top/bottom, but the full 320 pixels fit horizontally no problem.

**Comment by ihallin** [comment]
Yep, unfortunately still issues—rolling picture no matter what settings I tweak. Think it must just be ever so slightly out of spec for this monitor. Commodore 1942 and Trinitron flatscreen TV handle it just fine.

**Comment by mikaeltarquin** [comment]
This is a big improvement for my setup, apart from the audio, which almost sounds like it might be worse than Beta 3? It seems like it's barely coming through. Anyway, I'm sure you're well aware of the audio issues and hard at work on that. The video timing is a life saver, though! It's still a bit big on my 2530. I'm using H adjust -8 and V adjust +1, as well as some dial turning on my Extron Rxi to fit it, but at least now I can see most of the bomb meter and score number, and most of the left and right guages! Great work!

**Comment by nullobject** [comment]
I have added a 60Hz refresh rate option to the MiSTer menu.

This option can be enabled by anyone who has a CRT or HDMI display that isn't compatible with the original refresh rate.

The only downside is that it slightly alters the speed of the game, but I don't think most people would notice unless they are very familar with the original timings of the game.

Thanks for the original report @ihallin :+1:

**Comment by ihallin** [comment]
@nullobject so, weirdly, I just tried the 60hz option and it still doesn't sync on my PVM—it just causes the screen to roll more rapidly. I don't have this issue on any other cores so guessing there's just something else in the timings it doesn't like. ¯\_(ツ)_/¯
