### ISSUE TITLE
Layer priority issues (big white square)

### ISSUE THREAD

**Issue by huxmut** [nullobject/Arcade-Cave_MiSTer#14]
Sorry for the poor description, I get a large portion of the screen is white. the enemy bullets show, but the playfield/enemy does not.
pictures worth a million words hopefully ??
[url=https://ibb.co/BfBY0PB][img]https://i.ibb.co/7SK0szK/20201210-212241-HDR.jpg[/img][/url]

when i lost all my dudes and the continue screen appeared i was left with a window to see bits of the playfield/enemy
[url=https://ibb.co/g6nNq4j][img]https://i.ibb.co/SJLbYfs/20201210-212359-HDR.jpg[/img][/url]

sorry about the poor words. i'm super brain dead from a stressed out work week :/

**Comment by MonokromFR** [comment]
Same here.

Issue start from boss3 to stage4 end.
Then re-appears along stage6.

**Comment by nullobject** [comment]
Thanks for the report @huxmut and @MonokromFR.

> sorry about the poor words. i'm super brain dead from a stressed out work week :/

OMG, tell me about it. I am ending this year absolutely fried from work :dizzy_face:

**Comment by IcarusFW** [comment]
Just to elaborate a bit further: there's a huge off-center white layer that appears at the start of the stage 1-3 boss and persists until the start of stage 1-5. For the most part, the first time it appears, the game is still playable as bullets appear on top of it.

However, at the start of stage 1-6, it appears again, and this time it sits on top of the bullet layer, rendering the game from that point onwards completely unplayable.

Stage 1-3 boss clip: https://clips.twitch.tv/FunnyExpensiveBobaYouWHY
Stage 1-6 start clip: https://www.twitch.tv/icarusfw/clip/HilariousObesePlumberTBTacoLeft

**Comment by nullobject** [comment]
This has been fixed.
