### ISSUE TITLE
Score issue.

### ISSUE THREAD

**Issue by Akaifutari** [nullobject/Arcade-Cave_MiSTer#15]
Hi Josh! I'm testing the core right now and other than sound issues, I noticed a score issue. Is something weird. I don't know how to explain it (english is not my language :D) but the result is that the score is not real. Take a look at this pic. This is the end of the first stage. Also a layer priority issue appear.

![1607708809794](https://user-images.githubusercontent.com/60842648/101937355-0bb52280-3be2-11eb-9c59-54239a7b29c9.jpg)

**Comment by nullobject** [comment]
Thanks @Akaifutari, your english is great, thanks for the bug report :smile: 

You are correct. It must be caused by a layer priority issue, because there are digits missing from the score.

**Comment by nullobject** [comment]
Fixed :+1:
