### ISSUE TITLE
Corruption on Screen

### ISSUE THREAD

**Issue by EVAWINGZERO** [nullobject/Arcade-Cave_MiSTer#16]
Installed newest Version of the Beta Core, and when Booting I get this:

![PXL_20201215_203454274](https://user-images.githubusercontent.com/15805089/102274217-81c2cd80-3ef1-11eb-9ec7-29ad59eae58e.jpg)

I have tried different ROMs, Redownloading the MRA and RBF and tried different .ini settings. All other games run properly on this setup.

Any ideas?

**Comment by nullobject** [comment]
Hey thanks for reporting the issue @EVAWINGZERO :+1: 

I have a couple of questions:

* Does the game still run normally, although with garbled graphics?
* Do you have a CRT? If so, do you see the same issue when it's running with the analog video output?
* Are you running the latest version of the MiSTer OS? If you ran the `update.sh` script recently, then it should be fairly up to date.

**Comment by EVAWINGZERO** [comment]
Hey, thanks for the reply!

1. Game still runs normally just with the graphical issues.
2. Runing over VGA / IO - Game runs normally with no graphical issues.
3. Update script was run this morning, before messing with the HDMI settings.

**Comment by EVAWINGZERO** [comment]
Of course I write this, rerun the Mame getter (For the 5th or 6th time) and it pulls a new ROM......and all is working now. Sorry for wasting your time!

**Comment by nullobject** [comment]
> Of course I write this, rerun the Mame getter (For the 5th or 6th time) and it pulls a new ROM......and all is working now. Sorry for wasting your time!

All good. There could well be an issue there, so let me know if it keeps happening :+1:
