### ISSUE TITLE
End Scene Fails to complete

### ISSUE THREAD

**Issue by huxmut** [nullobject/Arcade-Cave_MiSTer#17]
My first time all the way to the end (i think it's the end??)
Sage looking dude sitting down and some cool music playing, but no words or story.
no button/s will end or complete. hard reset required

awesome :)

**Comment by nullobject** [comment]
Thanks. At least you got this far :stuck_out_tongue_winking_eye: 

My feeling is that it is related to the other layer priority issues, but I'm happy to have this captured in a separate issue :+1:

**Comment by huxmut** [comment]
re layer priority. 
yes, as i kind of expect some text about how the enemys were all my brothers, and now i must kill them all again. 
but no button would let me continue ... so is the lack of the layer appearing stopping the next sequence ?
anyway, bigger fish to fry for now 👍 
thanks for beta3 :)

**Comment by nullobject** [comment]
The text now appears during the end scene :heavy_check_mark:

I'm not sure why it crashes though, perhaps because the EEPROM hasn't been implemented yet?

**Comment by huxmut** [comment]
well this is weird.
i just played through and got  .... no text 👍 lol, but it didnt crash either .... the old guy sort of floated up a little like the there was text scrolling up underneath, but just a blank background. 
then it dropped back to the first attract screen ..

**Comment by nullobject** [comment]
> well this is weird.
> 
> i just played through and got  .... no text 👍 lol, but it didnt crash either .... the old guy sort of floated up a little like the there was text scrolling up underneath, but just a blank background. 
> 
> then it dropped back to the first attract screen ..

Interesting. I'll make another beta that includes the sprite layer fixes (which fixes the end text).

I'm not sure what fixed the crash at the end, or maybe it doesn't happen every time?

**Comment by huxmut** [comment]
I'm back to work from today (and on call to boot), so i'll try to get a 20 minute session in the next few days and test if the behaviour is consistant

**Comment by nullobject** [comment]
There is definitely text during the end scene now. Closing this issue, thanks @huxmut.

**Comment by huxmut** [comment]
Whoo Hoo ! 
👍
