### ISSUE TITLE
Video timings are off when compared with the PCB

### ISSUE THREAD

**Issue by loloC2C** [nullobject/Arcade-Cave_MiSTer#19]
The analog video output exhibits different timings and looks a bit stretched when compared with the PCB. 
(The issue appears with the all beta builds including the latest beta3).

I took 4 pictures in various game spots (using the same CRT monitor) and you can see the output is both horizontally stretched and shifted. (on the 4 pictures the core output is on top and the PCB output is at the bottom)

![Comparison01](https://user-images.githubusercontent.com/44382811/103279400-f99ef680-49cd-11eb-9164-f0c16f3aa038.jpg)
![Comparison02](https://user-images.githubusercontent.com/44382811/103279405-fad02380-49cd-11eb-8ab1-594d8a8ab123.jpg)
![Comparison03](https://user-images.githubusercontent.com/44382811/103279408-fc015080-49cd-11eb-949f-d94c65471647.jpg)
![Comparison04](https://user-images.githubusercontent.com/44382811/103279411-fd327d80-49cd-11eb-89dd-a4f07605bce4.jpg)

**Comment by nullobject** [comment]
Awesome, thanks for capturing this. It's super helpful (as always) to compare with a real PCB :heart:

On my CRT I've been using the "underscan" switch to enable the full image to appear. My Dangun Feveron PCB requires this too, so I just assumed DDP was the same.

I'll have a play around with the video timings to see if I can get the full image to appear using normal settings on my CRT.

**Comment by loloC2C** [comment]
I don't know if this is linked but the MiSTer's OSD appears way bigger than other cores with a similar resolution.

**Comment by Saroumane** [comment]
Hello, I don't have the PCB to compare, but I also have the "too big" picture problem (and I consider I have already "underscanned" my CRT, see the red part fully visible in the 240p suite test)
(Don't mind the whitish horizontal bar, it's a rolling artifact of my camera, not seen IRL.)

![ddptestCRT](https://user-images.githubusercontent.com/22261137/103389471-4b9b6580-4b0f-11eb-92a4-abb6546ebe27.jpeg)
![mire240psony](https://user-images.githubusercontent.com/22261137/103389474-4fc78300-4b0f-11eb-9ae2-c36645c9a916.jpg)

**Comment by nullobject** [comment]
@loloC2C Do you have an oscilloscope by any chance?

**Comment by nullobject** [comment]
@loloC2C @Saroumane This should be fixed. Could you please test beta 4 and let me know if this resolves your RGB timing issues? It's looking good on my CRT.

**Comment by bibou42** [comment]
Beta 3
The core syncs with the CRT (on the left) but we lose some parts of the screen.
I'm missing parts of the screen in all cores on this CRT but it's more in the Cave core.
I am using a Pal consumer TV (50/60Hz).

![DSCPDC_0003_BURST20210102205526767_COVER](https://user-images.githubusercontent.com/18500303/103474475-94b81780-4da4-11eb-9ab9-02e427eb1895.JPG)
![DSC_0103 3](https://user-images.githubusercontent.com/18500303/103474558-6be45200-4da5-11eb-8926-7b07f7b2089a.JPG)


Beta 4
We have more of the screen on the CRT but it doesn't sync anymore.

![DSCPDC_0000_BURST20210102205052480](https://user-images.githubusercontent.com/18500303/103474534-30e21e80-4da5-11eb-8fb7-cda402570c9f.JPG)
![DSCPDC_0001_BURST20210102205108464](https://user-images.githubusercontent.com/18500303/103474600-d8f7e780-4da5-11eb-9bb4-755aeab32a07.JPG)

**Comment by Saroumane** [comment]
Beta 4 / Beta 5 : with a bit of "V adjust" tweaking provided by your core, I have satisfying results (almost no cropping) on my roTATEd (Telefunken) TV. (maybe 2 lines offscreen)
On the other one (the Sony TV, non rotated) I still have 14 lines offscreen even with tweaking with "V adjust". But I won't use it for vertical games, so that's OK for me.

**Comment by nullobject** [comment]
Good to hear, and thanks for the original report @loloC2C.

I don't think I am ever going to match the video timings 100% to the original PCB (except for the vertical refresh rate @ 57.5Hz). I would much rather shoot for timings that have wider compatibity with MiSTer users.

If these are "close enough" for now, then I am going to close this issue. I'm certainly happy to make small tweaks to the timing values later if need be :+1:
