### ISSUE TITLE
Score error

### ISSUE THREAD

**Issue by Manuarcademaniac** [nullobject/Arcade-Cave_MiSTer#2]
Scores are not added correctly and it is erratic.

**Comment by nullobject** [comment]
Thanks for the report, it's certainly very strange. It may be some issue with the 8x8 tile layer :thinking:

**Comment by skeeter57** [comment]
Scores are still messed up, beta 2 release 12-10. Thanks.

**Comment by nullobject** [comment]
Fixed :+1:
