### ISSUE TITLE
Japanese MRA has wrong checksums

### ISSUE THREAD

**Issue by zakk4223** [nullobject/Arcade-Cave_MiSTer#21]
The japanese version MRA uses the checksums for the english u26.bin and u27.bin. 
(Mister loads by checksum first, then by rom name)

It probably works ok if your rom  is un-merged? For maximum split/merged/unmerged compatibility the checksums should be updated and the zip attribute changed to "dodonpach.zip|dodonpachj.zip"

**Comment by nullobject** [comment]
Ah, thanks for this. I am definitely running unsplit ROMS and I couldn't work out why the Japanese version wasn't working for some people. Will fix :+1:

**Comment by nullobject** [comment]
Hey @zakk4223, could you please re-download the MRA files (I updated them) from the Patreon post and try again? I will close this issue when you have confirmed it's all working.

**Comment by skeeter57** [comment]
I was having problems loading the JAP mra. The new mra has it working now for me, thanks!

**Comment by zakk4223** [comment]
Checksums are correct. If you update the zip="dodonpachj.zip" to zip="dodonpach.zip|dodonpachj.zip" you'll probably never get any more complaints about it not working, unless the person just has straight up broken roms

**Comment by nullobject** [comment]
@zakk4223 Oh cool, I didn't know you could do that.

Why would you need the alternate in that case, is that for merged ROMs?

**Comment by zakk4223** [comment]
Split or merged. In the split case the two JP program roms come from ddonpachj, but everything else is in ddonpach. Merged case everything is in ddonpach

If someone casually googles for roms they'll probably end up with split roms

**Comment by nullobject** [comment]
Really helpful, thanks @zakk4223. How did you learn about this syntax?

It's a shame that isn't fully documented in the wiki: https://github.com/mister-devel/main_mister/wiki/Arcade-Roms

**Comment by zakk4223** [comment]
I cheated: I wrote the initial lookup by crc and multi-zip file a year ago ;)

**Comment by nullobject** [comment]
Fair enough. Ok, well thanks again. I updated the Japanese MRA file with the changes you suggested. Closing this...
