### ISSUE TITLE
Sprite priority issue between star bonus and explosions

### ISSUE THREAD

**Issue by loloC2C** [nullobject/Arcade-Cave_MiSTer#3]
Beta version : Arcade-Cave_20200815.rbf

There's a sprite priority issue between explosions and stars bonus that can be noticed as early in the game as the 1st level. See the below captured screenshot:
![stars or explosiong priority](https://user-images.githubusercontent.com/44382811/90312045-8eaec080-df01-11ea-909b-5e8279993cf8.png)

**Comment by nullobject** [comment]
Perfect bug report, thanks. I will look into it :+1:

**Comment by nullobject** [comment]
This has been fixed :heavy_check_mark:
