### ISSUE TITLE
Sprite priority issue between boss and boss life bar

### ISSUE THREAD

**Issue by loloC2C** [nullobject/Arcade-Cave_MiSTer#4]
Beta version : Arcade-Cave_20200815.rbf

There's a sprite priority issue between the boss sprite and its life bar that can be noticed at the end of 
the 1st level. If I recall correctly rwk was aware of that issue.

See the below captured screenshot:
![boss priority](https://user-images.githubusercontent.com/44382811/90312082-e77e5900-df01-11ea-85e9-57f6d3d7ece1.png)

**Comment by nullobject** [comment]
This has been fixed :heavy_check_mark:
