### ISSUE TITLE
Sprite issue at start of the game.

### ISSUE THREAD

**Issue by Dubon77** [nullobject/Arcade-Cave_MiSTer#8]
At the start of the game, when the mothership drops you of, as it exits the screen to the bottom, for an instant its exhausts can be seen at the top of the screen.
It happens in this video at 1:50-1:51
https://youtu.be/4ImIDORy7sQ

In all the playthroughs ive looked at this doesnt appear to happen

**Comment by Dubon77** [comment]
![C2CEAD54-4D6B-4F0C-975F-8F97A904514D](https://user-images.githubusercontent.com/57742978/90320579-c853eb80-df42-11ea-8bdf-41b08dc88981.png)

**Comment by nullobject** [comment]
Fixed :+1:
