### ISSUE TITLE
Display issue when 2nd boss appears

### ISSUE THREAD

**Issue by loloC2C** [nullobject/Arcade-Cave_MiSTer#9]
Beta version : Arcade-Cave_20200815.rbf

There's a display issue with the boss of the 2nd level which seems to enter (wrongly) from the left side of the screen at first and then correctly from the right side as if its position was warped.

Here's a capture of the problem I posted on Youtube (unregistered): https://youtu.be/Vr9ShdnD0MU

**Comment by nullobject** [comment]
I can totally see it :eyes: Thanks for the capture.

**Comment by nullobject** [comment]
Fixed :+1:
